### ISSUE TITLE
Introduce the concept of IFD?

### ISSUE THREAD

**Issue by tejing1** [divnix/nix-book#17]
Somewhere in section `3. The Nix Language`, IFD should probably be explained. What it is, why it's useful, why it's problematic, and the fact that it's not allowed in nixpkgs.

**Comment by jonringer** [comment]
The goal of the nix language section was to equip them to start understanding material in later sections. I think IFD should be covered but it would be in a much later section.

Because IFD also has related concepts like pure-eval, strict-eval, and recursive nix. And I think I would rather visit those concepts after the vanilla concept of a derivation is cemented.

**Comment by tejing1** [comment]
Hmm, fair point. It's too much for an introduction.
